# Generated by Django 5.1 on 2024-08-19 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_add_new_registers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="register",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
